### ISSUE TITLE
Please  update go to version 1.23

### ISSUE THREAD

**Issue by weberhofer** [openSUSE/obs-service-go_modules#53]
For building traefik 3.1.3 go version would be needed:

> INFO:obs-service-go_modules:go mod download
> ERROR:obs-service-go_modules:go: go.mod requires go >= 1.23.0 (running go 1.22.7; GOTOOLCHAIN=local)
> ERROR:obs-service-go_modules:go mod download failed

**Comment by jfkw** [comment]
Thanks for the report. Has this resolved on your system? 

The default Go toolchain in the environment where the source service runs needs to be at least as new as the version specified in the go.mod file or any of its Go module dependencies, go1.23.0 in this case.

Around the time the issue was created, the go metapackage may not have yet updated from go1.22 to go1.23 on all repositories. go1.23 is the default now.

The go metapackage is an end-user convenience to install a recent version of Go with an easy to remember package name. Users can install a specific version such as go1.23 at any time. Packagers can and should use the expression `BuildRequires: golang(API) >= 1.23` in the RPM spec to pull in that version or any newer version at build time.

**Comment by weberhofer** [comment]
Other maintainers seems to have used the version successfully, therefor i think it has been resolved. Thanks for you explanations!
