### ISSUE TITLE
how to use this with obs_scm?

### ISSUE THREAD

**Issue by darix** [openSUSE/obs-service-go_modules#7]
## service file

```xml
<services>
  <service name="obs_scm">
    <param name="url">https://github.com/restic/restic.git</param>
    <param name="versionformat">@PARENT_TAG@+git@TAG_OFFSET@.%h</param>
    <param name="revision">master</param>
    <param name="scm">git</param>
    <param name="versionrewrite-pattern">v(.*)</param>
    <param name="versionrewrite-replacement">\1</param>
    <param name="changesgenerate">enable</param>
  </service>
  <service name="go_modules">
  </service>
  <service mode="buildtime" name="tar" />
  <service mode="buildtime" name="recompress">
    <param name="file">*.tar</param>
    <param name="compression">xz</param>
  </service>
  <service mode="buildtime" name="set_version" />
</services>
```

## log

```
${BASEDIR}/home:darix:restic/restic % ls -l ; ob-tw
total 24980
-rw-r--r--  1 darix users     1856 Aug 27 17:48 build.patch
drwxr-xr-x 11 darix users     4096 Aug 27 17:52 restic
-rw-r--r--  1 darix users     5862 Apr 11 22:00 restic.changes
-rw-r--r--  1 darix users     4117 Jan 10  2018 restic.keyring
-rw-r--r--  1 darix users     2781 Aug 27 17:54 restic.spec
-rw-r--r--  1 darix users       12 Aug 27 17:48 series
-rw-r--r--  1 darix users      711 Aug 27 17:56 _service
-rw-r--r--  1 darix users      234 Sep 28  2018 _servicedata
-rw-r--r--  1 darix users 25499149 Aug 27 17:56 _service:obs_scm:restic-0.9.6+git371.eb7c0038.obscpio
-rw-r--r--  1 darix users    27979 Aug 27 17:56 _service:obs_scm:restic.changes
-rw-r--r--  1 darix users      112 Aug 27 17:56 _service:obs_scm:restic.obsinfo
-rw-r--r--  1 darix users      234 Aug 27 17:56 _service:obs_scm:_servicedata
Building restic.spec for openSUSE_Tumbleweed/x86_64
Run source service: /usr/lib/obs/service/obs_scm --url https://github.com/restic/restic.git --versionformat @PARENT_TAG@+git@TAG_OFFSET@.%h --revision master --scm git --versionrewrite-pattern v(.*) --versionrewrite-replacement \1 --changesgenerate enable --outdir ${BASEDIR}/home:darix:restic/restic/tmp653y7_wr.obs_scm.service
Already up to date.
eb7c00387cb4d58e7bdcffbdc7389e0f8f605e69
Run source service: /usr/lib/obs/service/go_modules --outdir ${BASEDIR}/home:darix:restic/restic/tmp5cztvkr6.go_modules.service
INFO:obs-service-go_modules:Autodetecting archive since no archive param provided in _service
ERROR:obs-service-go_modules:Archive autodetection found no matching archive under ${BASEDIR}/home:darix:restic/restic
Aborting: service call failed:  /usr/lib/obs/service/go_modules --outdir ${BASEDIR}/home:darix:restic/restic/tmp5cztvkr6.go_modules.service
Source service run failed!
```

**Comment by nopeinomicon** [comment]
The go_modules service must be placed *after* the tar and recompress services as it is not compatible with the .obscpio archive. Those services generate the compatible archive. 

Also, as an aside, I'd like to mention that using the recompress function with obs_scm is redundant as explained [here](https://github.com/openSUSE/obs-service-tar_scm#obs_scm).

**Comment by darix** [comment]
well I do not want the services in disabled mode, but this is a setup for snapshot builds hooked up to git/cronjob. so I would need go_modules to work with the cpio file.

**Comment by nopeinomicon** [comment]
Ah, sorry for assuming, I'm very newbie. Regardless my first point stands, just move the go_modules service after the recompression and it would work.

**Comment by nopeinomicon** [comment]
Oh, and change the compression type from xz to gz if you are using the current release build, as that version lacks support for .xz archives. I put up an issue asking for a new version to be pushed so hopefully that will be fixed soon, but for now that change is necessary.

**Comment by darix** [comment]
with the obs_scm I can even build packages without ever generating a tarball and use the obs_scm directly.

as you can see here https://build.opensuse.org/package/view_file/home:darix:apps/discourse/_service?expand=1 e.g.

so what we actually want here is that obs_scm tells the further steps "the archive name is foo-x.y.z.obspcio" and the other steps just work based on that. it could be a field in the obsinfo file e.g..

but welcome to opensuse and our tooling!

**Comment by nopeinomicon** [comment]
Thanks! Yeah, I've had issues myself with trying to get this to work with obs_scm so it's a fun thing haha. Ig at this point it would be best for .obscpio support to be implemented here, though ofc I wouldn't have a clue how to go about that.

**Comment by jfkw** [comment]
Thanks for the discussion @darix and @nopeinomicon on the topic of archive formats supported. Please refer to the [hugo package](https://build.opensuse.org/package/show/devel:languages:go/hugo) for recommended usage. It is true `.obscpio` has not yet been added as a supported archive format, as I don't think the python standard library has support for the format. I have been holding off tagging a release with the `.xz` support merged on the master branch in order to first balance a few considerations:

- A general sense that obs_service_go-modules should default to one packaging convention suited for most cases with relatively few knobs as needed to handle edge cases, and a minimal required declaration in `_services`. Ideally when called without arguments it will normalize and migrate vendor archive name and format to the current convention when run. Overrides will be possible, but we want to keep soft system dependencies at a minimum for ease of deployment in OBS.
- `.tar.gz` archives compress well, but `.xz` compresses substantially better, at the cost of speed on OBS workers. It has been suggested that `.zstd` may in the future provide a better balance. After reading the docs I'm not clear on the relative merits of `.obscpio` which IIUC is an uncompressed format that gets mounted thus reducing compute overhead in OBS vs. `.xz` which is highly compressed but adds substantial compute overhead.
- `.xz` support requires a support package in some older distributions where Go would otherwise still work fine. If `.xz` is a supported format every go application package or OBS project may need to make provision for that soft dependency, adding developer overhead.
- Inspection of `vendor.tar.gz` is a common step in debugging builds. Many developers, myself included, have `.tar.gz` tar arguments memorized but need to look up tar arguments when infrequently using `.xz`, `.bz2` etc.. An `.obscpio` archive is challenging to unpack and inspect. Ease of use for developers is a valid consideration.

Thanks for the discussion, I'm glad to hear additional thoughts.

**Comment by darix** [comment]
Given that this is a generic problem, e.g. it also affects things like the cargo vendor service. or it could make the gem vendor service used by the OBS easier. I see it more as a question that we should solve at the OBS service level. so one service (obs_scm in this case) can communicate "hey i produced this output file, if you look for an archive you process, look at this" so we do not have to configure the tarball name in multiple places.

about cpio support in python ... maybe we could unify all our services around things like https://pypi.org/project/libarchive/ or just calling bsdtar.

**Comment by nopeinomicon** [comment]
I mean, I have been able to get the two services to work in tandem on OBS before with a mild level of difficulty here: https://build.opensuse.org/package/show/devel:tools:scm/gh (though the package still doesn't build as there is a dependency issue with obs_scm on Tumbleweed right now)

But that's really a pretty basic use case where i can afford the workarounds of changing around archive names and such, and having to repackage the cpio to a .tar.gz at buildtime, and from what you've said darix your use case doesn't seem to be able to work with that method, not even considering the lack of efficacy to the build workers having to repackage this every time. I don't have much to say to a solution however, that's just my experience with it.

**Comment by SchoolGuy** [comment]
So is there any update here? This hit me today sadly and I don't see movement for more then a year now.
